version: '3'
services:
  lb:
    build: lb
    ports:
      - "80:8080"
    depends_on: 
      - app
  db:
    build: db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: LIBRARIES
      MYSQL_USER: libuser
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: app
    depends_on: 
      - db