CREATE DATABASE IF NOT EXISTS LIBRARIES;

USE LIBRARIES;

DROP TABLE IF EXISTS library;

CREATE TABLE library(
  LIB_ID INT AUTO_INCREMENT PRIMARY KEY,
  NAME VARCHAR(255) NOT NULL,
  DOWNLOAD_COUNT INT NOT NULL,
  AUTHOR VARCHAR(255) NOT NULL,
  URL VARCHAR(255),
  REPOSITORY VARCHAR(255),
  VERSION VARCHAR(165),
  NOTES LONGTEXT
);

CREATE INDEX IDX_LIB_NAME_ ON library(NAME);
